### PR TITLE
Change to fetched if running locally

### PR DESCRIPTION
**Pull request by timkelty**
If you were running it locally, you'd want to do it on `fetched`, yes? 
So everything gets copied to the server.

### CODE REVIEW

**Comment by callerc1** [comment]
Yup this makes sense thanks for spotting that, tho pr is falling over on initial checkout. `Cannot read property 'npm' of undefined`

**Comment by timkelty** [comment]
Ah, right. It seems `shipit.initConfig` hasn't been called yet at this point, so we can't access those properties.

@neoziro, any ideas here? Basically, I think we want to access shipit config properties outside of a task definition.

**Comment by gregberge** [comment]
@timkelty do it in the task, it's easy.

**Comment by gregberge** [comment]
@timkelty it's just about architecture and implementation of your module, but effectively you can't access to the config before shipit has registered its config.

**Comment by callerc1** [comment]
@timkelty @neoziro i have updated the shipit-npm package just now which gets around this issue. specifically https://github.com/callerc1/shipit-npm/commit/82f4bf83a600c7fdcc85a0370eb3a030674e74a1

**Comment by timkelty** [comment]
@callerc1 are you running through Grunt? Your fix works for me in Grunt but not through `shipit` cli

**Comment by callerc1** [comment]
Nope just using shipit cli.

**Pull request closed without merging**
